
analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_import: ignore
    unused_element: ignore
    unused_field: ignore
    unused_import: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:

  rules:
